
name: Deploy FastAPI to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload backend to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./backend"
          target: "/home/ec2-user/app"

      - name: Restart FastAPI app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill uvicorn || true
            cd /home/ec2-user/app/backend
            pip3 install -r requirements.txt
            nohup uvicorn main:app --host 0.0.0.0 --port 80 &
